baseURL = 'https://mlfbvr.github.io/blog/'
languageCode = 'en-us'
title = "Martin Lefebvre's blog"
theme = "martin"

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']

